name: Build .Net 6
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: |
          dotnet restore DemoApp/Client/src/Client.csproj
          dotnet restore DemoApp/Server/src/Server.csproj
      - name: Build
        run: |
          dotnet build DemoApp/Client/src/Client.csproj
          dotnet build DemoApp/Server/src/Server.csproj
      - name: Publish
        run: |
          dotnet publish DemoApp/Client/src/Client.csproj
          dotnet publish DemoApp/Server/src/Server.csproj
