name: onPushWithParameter
on:
  push:
    branches: [main]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        id: step-one
        run: echo "field_step_one=MyValue Is 42" >> $GITHUB_OUTPUT
      - name: step two
        id: step-two
        run: echo "my out value is ${{ steps.step-one.outputs.field_step_one }}"
